-- AlterTable
ALTER TABLE "EntityWorkflowState" ADD COLUMN IF NOT EXISTS "attemptCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastContactedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "cooldownUntil" TIMESTAMP(3);
